_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.6
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
activation:
    value: relu
base_channels:
    value: 64
dropout_rate:
    value: 0.1
epochs:
    value: 200
learning_rate:
    value: 0.001
num_layers:
    value: 3
peak_weight:
    value: 0.3
scheduler:
    value: plateau
use_attention:
    value: true
use_residual:
    value: true
