_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.6
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
architecture:
    value: 3DCNN
batch_size:
    value: 64
early_stopping_patience:
    value: 15
epochs:
    value: 200
learning_rate:
    value: 0.001
loss_function:
    value: MSELoss
optimizer:
    value: Adam
scheduler:
    value: ReduceLROnPlateau
